language: bash
arch:
  - amd64
services:
  - docker
jobs:
  include:
    - stage: build branch
      script:
        - docker build -t chrisjohnson00/awx_proxy -f Dockerfile .
        - docker run chrisjohnson00/awx_proxy python -m pytest
        - docker run chrisjohnson00/awx_proxy python -m flake8
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/awx_proxy chrisjohnson00/awx_proxy:$TRAVIS_BRANCH
        - docker push chrisjohnson00/awx_proxy:$TRAVIS_BRANCH
      if: tag is blank
    - stage: build tag
      script:
        - docker build -t chrisjohnson00/awx_proxy -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/awx_proxy chrisjohnson00/awx_proxy:$TRAVIS_TAG
        - docker push chrisjohnson00/awx_proxy:$TRAVIS_TAG
        - docker push chrisjohnson00/awx_proxy
      if: tag IS present
