language: bash
env:
  global:
    - secure: "X8hf6xiKgvXMLF9nuE3U36NzLEJLy2MeBB7PcJzw+GKIxbyPBOz/ZnqIEEcx0gM1ulbLy3vZrjuvGRpbFWprmejuES2Ty2mpXnvhPN+Ri4bniFwBfCZfWBPhdvW95ig8RaIT3OVOpHNO5n6w2mRGU/1LZI/G4WGNmRU3zB9FOfRi5iarubhODFFWIyvtjP6t6DDf2VeYXXn+mdw8Geu/VguDu9Woudsg+Us0IMQdjLYHds8GAk9XLAywFvO2TbvuwDtJut2g2X3ji/qpmrwMfOxyy4zxjDbOykJ+N5heDXIZUspqd65BbiC4swfcHLd1ciT8Ce/v3gn7LA62V0edqdymhjhzfY/RlPIFdst2ILVZgekGPEZthkBkwv/7e+zEq8izrZf7Hkb2QTvgDOviDitjUi77t1YXYIyuV/MKwuvF6VejqeJO6SylQWQwiXFBSPggf/KK6f3Z/DCdSSeuStrffw/37n5GXyB7Qdl7M4THoavpj4yWNaDX38Z4GIIVHwjK3JBw0HkEplsW47MbdiaicJ1HEi091A8viadv6QKJ2vqyCK+uj1Ny0c9fFpNTwkDiV4WdeRqLhxGKFczVWSLzMc1VirsDBLyGCUpa0TciEhz5unWWv+t6BOZzFFcJ5fzK880DCdJdUWRFoBwUOQtPLl2k6bIYjgWA/7uyQcM="
arch:
  - arm64
services:
  - docker
script:
  - docker build -t cloud.canister.io:5000/chrisjohnson00/awx_proxy -f Dockerfile .
  - docker login cloud.canister.io:5000 --username=chrisjohnson00 --password=$CANISTER_PWD
  - docker push cloud.canister.io:5000/chrisjohnson00/awx_proxy
